https://www.mozilla.org/contribute/
https://www.mozilla.org/about/
https://forum.mxlinux.org/viewtopic.php?t=55034
https://www.howtogeek.com/devops/how-to-run-your-own-dns-server-on-your-local-network/
https://docs.vllm.ai/en/latest/models/supported_models.html
https://hackernoon.com/quantizing-large-language-models-with-llamacpp-a-clean-guide-for-2024
https://huggingface.co/collections/meta-llama/code-llama-family-661da32d0a9d678b6f55b933
https://news.ycombinator.com/item?id=37248494
https://www.snowflake.com/en/blog/meta-code-llama-testing/
https://docs.vllm.ai/en/latest/serving/serving_with_llamastack.html
https://medium.com/@yevhen.herasimov/serving-llama3-8b-on-cpu-using-vllm-d41e3f1731f7
https://www.reddit.com/r/LocalLLaMA/comments/1bxfms3/favorite_model_for_coding/
https://huggingface.co/spaces/bigcode/bigcode-models-leaderboard
https://dvynsh.org/blog/2024/llm-quantization/
https://ai.meta.com/blog/meta-llama-quantized-lightweight-models/
https://www.llama.com/docs/community-support-and-resources
https://www.llama.com/docs/llama-everywhere/running-meta-llama-on-linux/
https://www.llama.com/docs/integration-guides/meta-code-llama/
https://www.llama.com/docs/integration-guides/langchain/
https://www.llama.com/docs/integration-guides/llamaindex/
https://huggingface.co/collections/meta-llama/llama-32-66f448ffc8c32f949b04c8cf
https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct-QLORA_INT4_EO8
https://anaconda.org/conda-forge/transformers
https://www.restack.io/p/transformers-knowledge-transformers-cli-answer-cat-ai
https://huggingface.co/docs/huggingface_hub/main/en/guides/cli
https://huggingface.co/blog/codellama
https://llama-stack.readthedocs.io/en/latest/distributions/self_hosted_distro/remote-vllm.html
https://huggingface.co/lmsys/vicuna-7b-v1.1
https://huggingface.co/settings/tokens/new?tokenType=fineGrained
https://docs.vllm.ai/en/latest/quantization/gguf.html
https://huggingface.co/PrunaAI/codellama-CodeLlama-7b-Instruct-hf-bnb-4bit-smashed
https://huggingface.co/QuantFactory/CodeLlama-7b-Instruct-hf-GGUF
https://www.howtogeek.com/warp-ai-powered-linux-terminal/
https://txxx.com/videos/16545095/the-misty-luv-interview-just-the-truth-no-lies-misty-luv-50plusmilfs/?fr=18966475&rp=1
https://www.tgtube.com/search/thai%20trans%20compilation
https://www.fulltrannytube.com/view/1728930-traps-compilation
https://www.mozilla.org/en-US/contribute/
https://tomordonez.com/taskwarrior-task-management/
https://taskwarrior.org/docs/workflow/
https://www.cyberciti.biz/faq/debian-linux-wpa-wpa2-wireless-wifi-networking/
https://bbs.archlinux.org/viewtopic.php?id=243226
https://www.golinuxcloud.com/tmux-config/
https://www.redhat.com/sysadmin/learn-bash-scripting
https://www.hostinger.com/tutorials/bash-script-example
https://proprivacy.com/privacy-service/comparison/private-search-engines
https://www.makeuseof.com/tag/7-cool-html-effects-that-anyone-can-add-to-their-website-nb/
https://www.howtogeek.com/815778/bash-for-loops-examples/
https://stackoverflow.com/questions/51142253/add-python-support-to-vim
https://globe.adsbexchange.com/
https://www.radarbox.com/
https://www.airportia.com/
https://azero.dev/#/accounts
https://coingolive.com/en/coin/ath-price/
https://wiki.alpinelinux.org/wiki/Main_Page
https://am.i.mullvad.net/
https://www.amiunique.org/
https://godex.io/
https://anonfiles.com/
https://wiki.archlinux.org/
https://athcoinindex.com/
https://zer1t0.gitlab.io/posts/attacking_ad/
https://linuxhandbook.com/bash-automation/
https://blog.kyleavery.com/posts/avoiding-memory-scanners/
https://serverfault.com/questions/629778/which-open-source-program-is-similar-to-the-linux-dialog-command
https://stackoverflow.com/questions/25929369/which-open-source-program-is-similar-to-the-linux-dialog-command
https://linuxconfig.org/tag/bash
https://stackoverflow.com/questions/42371156/bash-dialog-inputbox-with-variable-entered
https://linuxconfig.org/bash-scripting-tutorial-for-beginners
https://academy.hackthebox.com/
https://www.privacytools.io/
https://bigbear.cx/
https://www.binance.com/en
https://iancoleman.io/bip39/
https://www.bitaddress.org/bitaddress.org-v3.3.0-SHA256-dec17c07685e1870960903d8f58090475b25af946fe95a734f88408cef4aa194.html
https://bitinfocharts.com/bitcoin/
https://www.blockonomics.co/
https://www.bitcoinwhoswho.com/
https://www.oulnilbdywxzdcchh5ne2hv24hfu76ealb5y6uibnclw3jjromboxhad.onion/
https://escaroo.com/
https://btcsniffer.com/
https://bitcoin-mix.org/
https://mixer.money/en/
https://threatmap.bitdefender.com/
https://bitly.com/
https://www.bitstamp.net/
https://blocktivity.info/
https://www.blockchain.com/
https://www.elliptic.co/
https://blockchaingroup.io/
https://txstreet.com/
https://www.blackhillsinfosec.com/blog/
https://samcurry.net/blog/
https://bloxy.info/
https://community.blueliv.com/map/
https://tenta.com/test/
https://browserleaks.com/
https://ux.stackexchange.com/questions/120001/alternatives-to-modal-dialog-for-simple-forms
https://www.bybit.com/en-US/
https://browserleaks.com/canvas
https://search.censys.io/
https://www.certik.com/
https://cezex.io/#/price-all
https://chainz.cryptoid.info/
https://changenow.io/
https://torguard.net/checkmytorrentipaddress.php?hash=65fd3f647d2a679bdc4ad2e47bbda2b1043eaba2
https://check.torproject.org/
https://chess.com/
https://www.chess.com/
https://ciphertrace.com/
https://randomgeekery.org/post/2021/05/cli-journaling-in-joplin-with-raku/
https://www.coinfirm.com/
https://coinmarketcal.com/en/
https://www.parrotsec.org/community
https://discordapp.com/invite/KEFErEx
https://www.guru99.com/data-communication-computer-network-tutorial.html
https://www.softwaretestinghelp.com/computer-networking-basics/
https://www.ohchr.org/en/instruments-mechanisms/instruments/convention-against-torture-and-other-cruel-inhuman-or-degrading
https://coveryourtracks.eff.org/
https://blog.self.li/post/74294988486/creating-a-post-installation-script-for-ubuntu
https://cassidy.codes/blog/2019-08-03-tmux-colour-theme/
https://www.geeksforgeeks.org/creating-dialog-boxes-with-the-dialog-tool-in-linux/
https://cryptobubbles.net/
https://coincodex.com/
https://messari.io/
https://cryptocoin.cc/
https://www.cryptocompare.com/
https://walletinvestor.com/converter
https://www.marketcapof.com/
https://coinmarketcap.com/
https://www.coingecko.com/
https://cryptorank.io/
https://cryptomixer.io/
https://cryptowat.ch/
https://crypt.parrot.sh/
https://crystalblockchain.com/
https://www.geeksforgeeks.org/custom-commands-linux-terminal/
https://www.cvedetails.com/
https://talosintelligence.com/fullpage_maps/pulse?__cf_chl_jschl_tk__=d8606de8e8d992f81979cff17898eac51835e80e-1615699239-0-AS8Ebf8Q8sHMWu1iKhC-l6hylqTP1PExnMqVp9OMbXnjXXGe4PwnTbDXfluWlzgEe5tW02keOWjQvDQzcJSv_0HMH9_cGhJd13AW9coDbCFA2jVzAvTEZzTe3KZm84D38oDN_kV1emLlyXZrDSJWU9R8sR4o5u9StkTIFyKzMYlPP7pdwDT4zUZmQEfyjFNsZIVzgK6RXyOwwyAYDJDZMFYBIc3n8dqV2ngGJxdUUQVn4cNw5KMWvANY3rg5Rq-BB4GM_WOOwAbqAPwWKnMEl6EWsPzHF-6lvXojUYyPlzZ1vq3I43DbDFQ2_JLxXWoNr3-A40GW287DtWRIfOy_VhF6TgDwv3LCQ1H0R2q7CSw9CLn1GBEk1lOakNH41FGjTPPWhaKviE8x1y9NyDCPok4tnKhqiqKDVxd4gt40Vr1i
https://www.hackthebox.com/hacker/infosec-careers
https://cointool.app/dashboard
https://www.debian.org/doc/user-manuals#debian-handbook
https://www.debian.org/doc/
https://www.deepl.com/
https://www.deepl.com/translator
https://defillama.com/
https://vimeo.com/user1690209
https://wallet.dero.io/
https://www.dexlab.space/mintinglab/spl-token
https://invisible-island.net/dialog/
https://alternativeto.net/software/dialog/?platform=linux
https://www.digitalattackmap.com/#anim=1&color=0&country=ALL&list=0&time=18205&view=map
https://www.hxuzjtocnzvv5g2rtg2bhwkcbupmk7rclb6lly3fo4tvqkk5oyrv3nid.onion/
https://www.top10vpn.com/tools/do-i-leak/
https://wiki.alpinelinux.org/wiki/Dualbooting
https://www.earthcam.com/
https://alternativeto.net/software/easybashgui/about/
https://easyos.org/
https://www.digi77.com/
https://eff.org/
https://emailselfdefense.fsf.org/
https://escrow.counos.io/
https://www.etherchain.org/
https://ether-mixer.org/start-mixing.html
https://thecoinperspective.com/
https://ethplorer.io/
https://explainshell.com/explain?cmd=pandoc
https://www.exploit-db.com/
https://cxsecurity.com/exploit/
https://exploit.education/
https://vi.stackexchange.com/questions/39627/export-libreoffice-thesaurus-to-vim-compatible-format-with-a-macro
https://filen.io/
https://www.filterbypass.me/
https://hunter.io/
https://www.fireeye.com/cyber-map/threat-map.html
https://stackoverflow.com/questions/946189/how-can-i-set-default-homepage-in-ff-and-chrome-via-javascript
https://wiki.mozilla.org/Firefox/CommandLineOptions
https://www.fisgonia.com/
https://fixedfloat.com/
https://www.flippening.watch/
https://threatmap.fortiguard.com/
https://freecomputerbooks.com/
https://www.tandfonline.com/doi/full/10.1080/14753634.2013.778485
https://learn.go.dev/
https://go.dev/learn/
https://ghostbin.com/
https://www.givero.com/
https://gnupg.org/documentation/howtos.html
https://goo.gl/
https://viz.greynoise.io/
https://forum.hackthebox.com/
https://www.hackthebox.com/blog
https://help.hackthebox.com/en/
https://www.hackthebox.com/
https://www.hackthebox.com/hacker/hacking-labs
https://humanrights.gov.au/quick-guide/12040
https://vault.havenprotocol.org/
https://hide.me/en/proxy
https://linuxjourney.com/
https://wiki.alpinelinux.org/wiki/Hosting_Web/Email_services_on_Alpine
https://vi.stackexchange.com/questions/7656/how-do-i-get-multiple-vimwikis-to-show-under-vimwiki-open-index-in-the-gvim
https://www.unixmen.com/access-twitter-via-command-line-terminal/
https://www.cyberciti.biz/faq/sudo-append-data-text-to-file-on-linux-unix-macos/
https://www.techrepublic.com/article/how-to-clone-a-website-with-httrack/
https://www.howtogeek.com/278599/how-to-combine-text-files-using-the-cat-command-in-linux/
https://computingforgeeks.com/how-to-configure-mpd-and-ncmpcpp-on-linux/
https://opensource.com/life/15/3/creating-split-screen-shots-kdenlive
https://medium.com/devnetwork/how-to-create-your-own-custom-terminal-commands-c5008782a78e
https://linuxhint.com/customize-tmux-configuration/
https://stackoverflow.com/questions/39337075/how-to-delete-text-between-all-braces-in-vim
https://www.geekyhacker.com/2021/08/02/how-to-fix-grub-i386-pc-normal-mod-no-found/
https://itigic.com/install-and-configure-dlna-minidlna-server-on-linux/
https://howtoforge.com/how-to-install-koel-music-streaming-server-using-docker-on-rocky-linux-8/
https://www.linuxshelltips.com/install-xfce-alpine-linux/
https://9to5linux.com/how-to-search-for-text-within-files-and-folders-in-linux
https://medium.com/@jimmashuke/how-to-stop-that-annoying-sudo-password-prompt-in-linux-b2b72b9c2f55
https://www.howtogeek.com/734838/how-to-use-encrypted-passwords-in-bash-scripts/
https://www.techrepublic.com/article/how-to-use-secure-copy-with-ssh-key-authentication/
https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced
https://mirror.parrot.sh/parrot/misc/openbooks/
https://itsubuntu.com/how-to-install-deepin-desktop-environment-on-ubuntu-22-04-lts/
https://docs.docker.com/engine/install/debian/#set-up-the-repository
https://docs.docker.com/desktop/install/debian/
https://wiki.alpinelinux.org/wiki/Install_to_disk
https://international.bittrex.com/
https://ipleak.net/
https://ipinfodb.com/
https://www.perturb.org/content/iptables-rules.html
https://iptablesgenerator.totalbits.com/
https://ip6.nl/
https://docs.oracle.com/javase
https://0x64marsh.com/?p=314
https://keybase.io/
https://www.mlyusr6htlxsyc7t2f4z53wdxh3win7q3qpxcrbam6jf3dmua7tnzuyd.onion/
https://eirenicon.org/knowledge-base/
https://www.digi77.com/software/kodachi/Kodachi-Log.txt
https://www.kucoin.com/
https://kycnot.me/
https://learn-bash.org/
https://www.learn-c.org/
https://www.learn-cpp.org/
https://dev.java/learn/
https://nim-lang.org/learn.html
https://nodejs.dev/learn
https://www.learn-php.org/
https://www.learnpython.org/
https://superuser.com/questions/1224532/get-links-from-an-html-page
https://unix.stackexchange.com/questions/452101/how-to-keep-only-latest-file-in-the-folder-and-move-older-files-to-archive-locat
https://linuxcommand.org/lc3_adv_dialog.php
https://www.foxinfotech.in/2019/04/linux-dialog-examples.html
https://www.cyberciti.biz/security/howto-linux-hard-disk-encryption-with-luks-cryptsetup-command/
https://www.digi77.com/linux-kodachi/
https://thenewstack.io/linux-lesson-copy-files-over-your-network-with-scp/
https://docs.docker.com/engine/install/linux-postinstall/#configuring-remote-access-with-systemd-unit-file
https://redtm.com/privilege-escalation/linux-privilege-escalation-cheat-sheet/
https://chessentials.com/chess-tactics/
https://www.spamhaus.com/threat-map/
https://threatmap.checkpoint.com/
https://flightaware.com/live/
https://www.livefromiceland.is/
https://satellitemap.space/
https://mobility.portal.geops.io/
https://in-the-sky.org/satmap_worldmap.php
https://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
https://www.cryptocompare.com/portfolio/
https://cybermap.kaspersky.com/
https://mempool.space/
https://metager.org/
https://mint.bitcoin.com/#/configure
https://www.morphtoken.com/
https://pastebin.com/P7rwMFLq
https://magazine.odroid.com/article/multi-screen-desktop-using-vnc-part-2-an-improved-and-simplified-version/
https://www.thelinuxrain.org/articles/multiple-item-data-entry-with-yad
https://forum.mxlinux.org/
https://mxlinux.org/wiki/
https://wallet.mymonero.com/
https://pastebin.com/yZM8zGwv
https://medium.com/geekculture/neovim-configuration-for-beginners-b2116dbbde84
https://raspberrypi.stackexchange.com/questions/110799/wifi-not-working-after-installing-openmediavault-omv-5-in-rpi-4
https://www.computernetworkingnotes.com/networking-tutorials/
https://www.neutrino.nu/
https://phoenixnap.com/kb/nmap-command-linux-examples
https://nomics.com/
https://nvd.nist.gov/
https://csandker.io/2021/01/10/Offensive-Windows-IPC-1-NamedPipes.html
https://csandker.io/2021/02/21/Offensive-Windows-IPC-2-RPC.html
https://csandker.io/2022/05/24/Offensive-Windows-IPC-3-ALPC.html
https://messari.io/onchainfx
https://www.3bbad7fauom4d6sgppalyqddsqbf5u5p56b5k5uk2zxsy3d6ey2jobad.onion/
https://onionmail.org/
https://www.pflujznptk5lmuf6xwadfqy6nffykdvahfbljh7liljailjbxrgvhfid.onion/
https://www.zend2.com/#
https://www.onlineotp.com/
https://sourceforge.net/blog/projects-of-the-week-april-24-2017/oolite/
https://wiki.alioth.net/index.php/Oolite_Main_Page
https://www.openrailwaymap.org/
https://www.opentraintimes.com/maps
https://wizard.openzeppelin.com/
https://prism-break.org/en/
https://www.python.org/doc/
https://overland.org.au/
https://www.owasp.org/
https://owasp.org/www-project-secure-coding-dojo/
https://owasp.org/www-project-webgoat/
https://packetstormsecurity.com/
https://panopticlick.eff.org/
https://start.parrot.sh/
https://www.parrotsec.org/
https://www.parrotsec.org/docs
https://www.parrotsec.org/docs/
https://bitwarden.com/help/cli/
https://pentesterlab.com/
https://www.phobosxilamwcg75xt22id7aywkzol6q6rfl2flipcqoc4e4ahima5id.onion/
https://php.net/manual/en/index.php
https://www.digitalneanderthal.com/post/ncmpcpp/
https://wiki.alpinelinux.org/wiki/Post_installation
https://vim.fandom.com/wiki/Power_of_g
https://privatebin.net/
https://0xsp.com/offensive/privilege-escalation-cheatsheet/
https://wiki.gnome.org/action/show/Projects/Zenity?action=show
https://protonmail.com/
https://www.proxysite.com/
https://www.brewology.com/?cat=4
https://saterahsia.com/ps3-hfw-4-89-hybrid-firmware-latest-update-v4-89-1/
https://www.brewology.com/psn/downloader.php?ref=news
https://almal3eb.com/2022/05/30/ps3-cfw-evilnat-4-89-2-beta-released-wololo-net/
https://www.qrcode-monkey.com/
https://quad9.net/
https://www.qubes-os.org/
https://www.qwant.com/
https://www.reddit.com/r/vim/comments/nwi7d8/terminal_sexy_but_for_vim/
https://docs.alpinelinux.org/
https://tracker.habhub.org/
https://pack.resetthenet.org/
https://restoreprivacy.com/
https://stackoverflow.com/posts/41463292/revisions
https://www.baeldung.com/linux/run-command-start-up
https://geoxc-apps2.bd.esri.com/Visualization/sat2/index.html
https://vi.stackexchange.com/questions/8839/how-i-configure-vim-for-use-with-netrw
https://vi.stackexchange.com/questions/19357/search-through-entire-vimwiki
https://securityinabox.org/en/
https://stackoverflow.com/questions/2512362/how-can-i-can-insert-the-contents-of-a-file-into-another-file-right-before-a-spe
https://unix.stackexchange.com/questions/99350/how-to-insert-text-before-the-first-line-of-a-file
https://unix.stackexchange.com/questions/337435/sed-insert-file-at-top-of-another
https://www.anonymousspeech.com/
https://tuomassalmi.com/tech/personal-wiki/
https://www.abs.gov.au/articles/sexual-harassment
https://stackoverflow.com/questions/2314750/how-to-assign-the-output-of-a-bash-command-to-a-variable
https://stackoverflow.com/questions/37644634/how-to-use-bash-dialog-yesno-correctly
https://www.freecodecamp.org/news/shell-scripting-crash-course-how-to-write-bash-scripts-in-linux/
https://www.shodan.io/
https://simpleswap.io/
https://www.redtube.com/playlist/3434751
https://chain.so/
https://lunarcrush.com/
https://www.social-searcher.com/
https://securitycenter.sonicwall.com/m/page/worldwide-attacks
https://securitycenter.sonicwall.com/m/page/capture-labs-threat-metrics
https://speedsmart.net/
https://www.speedtest.net/
https://www.redhat.com/sysadmin/sshfs
https://www.ssllabs.com/ssltest/viewMyClient.html
https://startpage.com/
https://www.startpage.com/
https://tutorialforlinux.com/2021/06/27/step-by-step-samba-file-sharing-on-mx-linux/3/
https://ssd.eff.org/
https://www.vim.org/scripts/script.php?script_id=3465
https://tails.boum.org/
https://kb.mozillazine.org/Talk:Firefox_links
https://taskwarrior.org/docs/30second/
https://taskwarrior.org/docs/best-practices/
https://taskwarrior.org/docs/configuration/
https://randomgeekery.org/post/2020/01/taskwarrior-sync/
https://mail.tm/en/
https://test-ipv6.com/
https://www.ubuntupit.com/simple-yet-effective-linux-shell-script-examples/
https://www.psychologytoday.com/us/blog/cutting-edge-leadership/201811/the-5-steps-dehumanization
https://guide.bash.academy/
https://www.chainalysis.com/
https://www.debian.org/doc/manuals/debian-handbook/index.en.html
https://www.opensuse.org/
https://www.documentary24.com/the-science-of-vacation--3191/
https://map.lookingglasscyber.com/
https://threatbutt.com/map/
https://web.threema.ch/#!/welcome
https://timewarrior.net/support/
https://timewarrior.net/docs/what/
https://www.torproject.org/
https://www.xmh57jrknzkhv6y3ls3ubitzfqnkrwxhopf5aygthi7d6rplyvk3noyd.onion/
https://opensecuritytraining.info/Training.html
https://www.pxdmqka7qbymz6xqs3cl3zmautwq6qf2p6fptf4u4hpddniyw2skziad.onion/
https://tutanota.com/
https://stackoverflow.com/questions/66866818/how-to-change-nvim-path-to-config
https://manpages.ubuntu.com/manpages/kinetic/en/man1/pandoc.1.html
https://askubuntu.com/questions/500359/efi-boot-partition-and-biosgrub-partition
https://www.thegeekdiary.com/how-to-install-and-configure-mutt-in-centos-rhel/
https://opensource.com/article/20/1/vim-task-list-reddit-twitter
https://mxlinux.org/manuals/
https://mxlinux.org/videos/
https://medium.com/@felipe.anjos/vim-for-web-development-html-css-in-2020-95576d9b21ad
https://www.naperwrimo.org/wiki/index.php?title=Vim_for_Writers
https://shapeshed.com/vim-netrw/
https://www.freecodecamp.org/news/vimrc-configuration-guide-customize-your-vim-editor/
https://vi.stackexchange.com/questions/28505/vimwiki-create-a-smart-index-page-for-subdir-section-of-wiki
https://pypi.org/project/vimwiki-cli/
https://dev.to/psiho/vimwiki-how-to-automate-wikis-per-project-folder-neovim-3k72
https://vuldb.com/
https://www.vulnerability-lab.com/
https://www.vx-underground.org/
https://www.walletexplorer.com/
https://twitter.com/warith2020?lang=en
https://www.linkedin.com/in/warith1977/
https://developer.mozilla.org/en-US/docs/Web/API
https://portswigger.net/web-security
https://worldcam.eu/
https://linuxconfig.org/webdav-server-setup-on-ubuntu-linux
https://uefi.org/
https://www.psychologytoday.com/us/blog/the-web-violence/201806/what-is-dehumanization-anyway
https://www.techtalk7.com/what-vim-command-to-use-to-delete-all-text-after-a-certain-character-on-every-line-of-a-file/
https://whoer.net/
https://wigle.net/
https://wpscan.com/wordpresses
https://patchstack.com/database/
https://satellites.pro/
https://www.nsupdate.info/
https://alternativeto.net/software/wxglade/about/
https://unix.stackexchange.com/questions/378373/add-virtual-output-to-xorg
https://www.x86matthew.com/
https://xsinator.com/
https://bbs.archlinux.org/viewtopic.php?id=202463
https://eirenicon.org/knowledge-base/yad-yet-another-dialog/
https://yad-guide.ingk.se/html/yad-html.html
https://codeberg.org/NRZCode/yad-examples/src/branch/master/player.sh
https://codeberg.org/NRZCode/yad-examples/src/branch/master/sysinfo-notebook.sh
https://codeberg.org/NRZCode/yad-examples/src/branch/master/tabs.sh
https://alternativeto.net/software/yad/about/
https://alternativeto.net/software/zenity/about/
https://www.zoomeye.org/
https://www.ethtective.com/
https://mxlinux.org/mx-linux-blog/
https://antixlinux.com/
https://www.antixforum.com/
https://plato.stanford.edu/
https://www.infoplease.com/
https://oxfordre.com/
https://www.encyclopedia.com/
https://www.merriam-webster.com/
https://www.britannica.com/
https://stackoverflow.com/questions/38924659/powershell-multi-choice-menu-and-sub-menu
https://www.rosipov.com/blog/custom-templates-in-vimwiki/
https://wiki.alpinelinux.org/wiki/Nextcloud
https://hub.docker.com/_/nextcloud/
https://nixos.org/manual/nixos/stable/#sec-installation-manual
https://nixos.org/manual/nixos/stable/
https://wiki.alpinelinux.org/wiki/Installation
https://docs.alpinelinux.org/user-handbook/0.1a/index.html
https://wiki.alpinelinux.org/wiki/Alpine_setup_scripts
https://docs.alpinelinux.org/user-handbook/0.1a/Installing/setup_alpine.html
https://www.upworthy.com/a-robot-whose-sole-purpose-is-to-connect-emotionally-with-cancer-patients-its-working-too
https://www.upworthy.com/videos
https://www.verywellmind.com/psychology-4157187
https://trisquel.info/en/forum/vbox-additions-trisquel#comment-121732
https://weather.com/en-GB/
https://communitylegalqld.org.au/webinar/human-rights-advocacy-tool
https://www.statelibraryofiowa.org/
https://www.samsung.com/au/apps/bixby/
https://www.health.nsw.gov.au/tobacco/Pages/tools-for-health-professionals.aspx
https://www.accc.gov.au/media-release/summary-of-trade-practices-act-1974-issued-by-accc
https://www.australiancompetitionlaw.org/legislation/1974tpa.html
https://www.legislation.nsw.gov.au/#/
https://www.legislation.nsw.gov.au/#/browse/asMade/acts/H
https://www.sl.nsw.gov.au/
https://evernote.com/
https://www.facs.nsw.gov.au/myhousing
https://account.samsung.com/membership/main
https://www.wsws.org/
https://neurosciencenews.com/music-synchronizes-brainwaves-eeg-10871/
https://www.mindbodygreen.com/articles/anxious-beginning-relationships
https://www.lesswrong.com/
https://www.psychologytoday.com/intl/articles/199301/the-power-the-unpredictable
https://www.humanitix.com/
https://www.radlivin.com/
https://blog.ing.com.au/beyond-banking/dreamstarter/dreamstarter-inspires-future-social-changers-via-radlivin-festival/#article-1869
https://help.twitter.com/en/managing-your-account/log-in-issues
https://philosophy.stackexchange.com/
https://fractalenlightenment.com/tag/transformation
https://fractalenlightenment.com/category/philosophy
https://www.academia.edu/38705066/International_Journal_of_Organization_Theory_and_Behavior_Integrating_video_technology_and_administrative_practice_in_policing_A_phenomenological_expos%C3%A9_Article_information?email_work_card=view-paper
https://www.hri.global/
https://m.slashdot.org/
https://weather.com/en-GB/weather/radar/interactive/l/c9e870a28a58cb496d8ff8beaedb967c919d0f7d8450acb2151347bc690d6f3a
https://www.hotelscombined.com.au/Hotels/Search?destination=place%3ANew_York_City
https://www.hri.global/hr19-programme?utm_source=HR19+Conference
https://weather.com/en-GB/weather/hourbyhour/l/6995307aef6d2360b6a43e4ebb68ebb2ea1f931bc3882f96124fbca38248e7d5
https://www.greenleft.org.au/
https://onbeing.org/
https://onbeing.org/series/podcast/
https://neurosciencenews.com/
https://www.instagram.com/neurosciencenew/
https://www.9news.com.au/national/coronavirus-sydney-scare-as-china-heads-into-shutdown/71c2e099-d49b-42b9-b4b1-02bc4a0457a6?ref=BP_RSS_ninenews_0_-grave-situation--as-coronavirus-claims-another-life_260120
https://apply.indeed.com/indeedapply/s/resumeApply
https://www.news.com.au/
https://www.news.com.au/technology
https://www.gumtree.com.au/
https://www.top10vpn.com/guides/vpn-leak-test/#which-vpns-leak-your-data-90-tested
https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/
https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/#
https://medicalfuturist.com/magazine
https://www.computerworld.com/article/3268630/android-apps-best-of-the-best.html#tk.ctw-infsb
https://thenextweb.com/
https://www.salon.com/2017/11/05/best-political-podcasts/
https://www.sas.upenn.edu/~jtreat/progressive.html
https://www.electionprojection.com/blogs/politics-and-election-news/
https://iai.tv/video/cybersecurity-and-huawei-nigel-inkster-interview?utm_source=newsletter
https://progressive.org/magazine/more-money-no-problem-leanza/
https://www.mayoclinic.org/about-this-site/advertising-sponsorship-policy
https://the-rachel-maddow-show.simplecast.com/episodes/what-will-the-new-attorney-general-face-at-the-doj-in-the-wake-of-trumps-abuses-oO_81twN
https://weather.com/weather/hourbyhour/l/b08a0496fddb8b724472dd110cded234b90fd334da006284a18dcd252895678f?par=samsung_widget#detailIndex0
https://www.reddit.com/register
https://conceptsphilosophy.wordpress.com/
https://www.reddit.com/r/PoliticalPhilosophy/
https://www.collective-evolution.com/
https://www.reddit.com/r/philosophy/
https://www.solidarity.net.au/
https://vimeo.com/143087954
https://forms.svha.org.au/svhs-visit/?specificLocation=yes
https://lichess.org/training
https://fieldofvision.org/
https://www.chess.com/game/live/72652538411
https://mobile.nytimes.com/blogs/learning/2016/02/24/our-100-most-popular-student-questions-for-debate-and-persuasive-writing/?referer=
https://www.smh.com.au/by/tom-rabe-h1f8u2
https://lichess.org/
https://codepen.io/challenges/
https://m.ebay.com/sch/i.html?_from=R40
https://www.chess.com/play/online/new
https://nimble.com.au/
https://www.shf.org.au/membership-volunteering/volunteering-with-the-fleet/
https://www.marxists.org/audiobooks/index.htm
https://www.marxists.org/
https://evolutioncounseling.com/grief-supposed-hurt/
https://whatsyourgrief.com/grief-podcast/
https://www.stitcher.com/podcast/whats-your-grief-podcast-series-grief-support-for-those-who/e/50379562
https://www.theguardian.com/tv-and-radio/2016/dec/21/the-50-best-podcasts-of-2016
https://thesocietypages.org/officehours/
https://www.vodafone.com.au/foundation/dreamlab
https://www.socialsciencespace.com/author/socialsciencebites/
https://thesocietypages.org/improv/
https://www.waysidechapel.org.au/
https://salvos.org.au/sydneystreetlevel/
https://www.reddit.com/r/sociology/comments/21rk2r/what_are_some_good_sociological_podcasts/
https://www.volunteeringaustralia.org/
https://m.soundcloud.com/partially-examined-life
https://qz.com/1049870/half-the-time-unpaywall-users-search-for-articles-that-are-legally-free-to-access/
https://m.ebay.com/itm/Outdoor-USB-WiFi-Adapter-150Mbps-13dBi-High-Power-WiFi-Antenna-Signal-Receiver/112584450204?hash=item1a368e609c:g:ShAAAOSwRrlZ-nDj
https://www.screenaustralia.gov.au/the-screen-guide/t/missing-persons-unit-series-2-2007/24188/
https://www.screenaustralia.gov.au/about-us/corporate-documents/policies/freedom-of-information
https://www.brainpickings.org/
https://www.techlicious.com/guide/the-best-news-aggregation-sites/
https://www.salon.com/2018/01/18/the-end-of-the-dream-portlandia-kicks-off-its-final-season/
https://www.democracynow.org/
https://partiallyexaminedlife.com/
https://www.learnoutloud.com/Free-Audio-Video/Social-Sciences/-/Introduction-to-Sociology/43635
https://www.learnoutloud.com/Free-Courses/Social-Sciences/Sociology
https://notesonliberty.com/2018/01/03/law-and-liberty-hobbesians-vs-rechtsstaaters/
https://www.omh.ny.gov/omhweb/cogdys_manual/CogDysHndbk.htm
https://www.medicinenet.com/dysthymia/article.htm
https://www.webmd.com/depression/features/anxiety-depression-mix
https://www.eventbrite.com.au/e/mental-health-first-aid-2-day-training-course-tickets-42663159659?aff=eac2
https://vi.stackexchange.com/questions/627/how-can-i-change-vims-start-or-intro-screen
https://vi.stackexchange.com/questions/30957/color-a-call-appendline
https://stackoverflow.com/questions/22697414/appending-to-a-file-with-linux-system-call
https://stackoverflow.com/questions/55860391/how-to-split-a-line-of-text-and-append-that-line-to-each-element-in-scala-spark
https://openai.com/chatgpt
https://linuxhandbook.com/seq-command/
https://linuxhandbook.com/bash/
https://www.kali.org/
https://www.kali.org/tools/
https://www.kali.org/docs/
https://forums.kali.org/
https://www.kali.org/kali-nethunter/
https://www.offsec.com/
https://support.mozilla.org/en-US/questions/1382056
https://linuxhandbook.com/usermod-command/
https://www.simplified.guide/linux/automatically-run-program-on-startup#running-a-program-automatically-on-new-bash-session
https://www.simplified.guide/linux/automatically-run-program-on-startup
https://www.usessionbuddy.com/post/How-to-Enable-Autocomplete-For-Command-Line-History-In-Bash-and-Zsh/
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Extension_pages
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
https://unix.stackexchange.com/questions/105424/mirroring-a-pane-between-two-windows
https://www.pgnmentor.com/files.html#openings
https://chess.stackexchange.com/questions/19633/chess-problem-database-with-pgn-or-fen
https://chessentials.com/chess-pgn-downloads/
https://unix.stackexchange.com/questions/141100/extracting-a-string-from-fdisk-command
https://stackoverflow.com/questions/18127245/using-the-output-of-fdisk-l-grep-disk-to-put-in-an-if-statement
https://linuxconfig.org/creating-a-bootable-usb-for-windows-10-and-11-on-linux
https://askubuntu.com/questions/1094540/how-can-i-recover-my-files-and-my-system-after-running-rm-r-home-username#comment1802381_1094540
https://www.freecodecamp.org/news/build-your-own-dotfiles-manager-from-scratch/
https://www.mailgun.com/blog/product/building-an-sms-to-email-gateway/
https://www.systranbox.com/configuring-an-sms-gateway-server-in-linux/
https://docs.oracle.com/cd/E61905_01/doc.100/e61907/im_config_sms_gtway_im.htm#IMSAG389
https://docs.oracle.com/cd/E61905_01/doc.100/e61907/im_conf_cal_agt_cal_ser.htm#IMSAG408
https://www.xmodulo.com/how-to-run-fdisk-in-non-interactive-batch-mode.html
https://www.baeldung.com/linux/usb-drive-format
https://www.parrotsec.org/community/
https://www.parrotsec.org/team/
https://www.parrotsec.org/donate/
https://speakerdeck.com/s1r1us/electrovolt-pwning-popular-desktop-apps-while-uncovering-new-attack-surface-on-electron
https://pypi.org/project/radicale-remind/
https://pypi.org/project/twc/
https://pypi.org/project/tw-hooks/
https://pypi.org/project/notmuchtask/
https://radicale.org/master.html#documentation
https://www.parrotsec.org/donate
https://humanrights.gov.au/quick-guide/12030
https://linuxjourney.com/lesson/the-shell
https://www.httrack.com/html/abuse.html
https://learnvimscriptthehardway.stevelosh.com/chapters/12.html
https://www.computerhope.com/
https://www.gnu.org/software/screen/
https://invisible-island.net/xterm/xterm.html
https://unix4lyfe.org/xterm/
https://superuser.com/questions/137423/config-files-for-xterm
https://how-to.fandom.com/wiki/How_to_configure_xterm
http interface to search a torrent by a keyword</A>
https://www.momvids.com/videos/11387/yvi-sie-heisst-uschi-und-ihr-juckt-die/?sub=100001
https://www.w3docs.com/learn-html/html-form-templates.html
https://docs.xfce.org/xfce/thunar/thunar-shares-plugin
https://pypi.org/project/thunar-plugins/
https://linuxconfig.org/how-to-extend-the-thunar-file-manager-with-custom-actions
https://decodechess.com/pricing-plans/
https://sourceforge.net/projects/chess-engines-for-android/files/Samsung
https://linuxconfig.org/configuring-the-mpd-music-server-on-ubuntu-linux
https://docs.funkwhale.audio/installation/debian.html
https://retropie.org.uk/docs/Debian/
https://www.theguardian.com/commentisfree/2019/mar/22/death-human-right-assisted-dying
https://mxlinux.org/wiki/applications/docker/
https://wiki.gentoo.org/wiki/Handbook:AMD64
https://www.systranbox.com/how-to-install-nvidia-drivers-in-mx-linux/
https://www.eduardoaleixo.com/posts/2022/vimwiki-diary-template/
https://www.makeuseof.com/install-configure-mutt-with-gmail-on-linux/
https://www.how2shout.com/linux/how-to-install-docker-engine-on-alpine-linux/
https://wiki.gentoo.org/wiki/Install_Gentoo_on_a_bootable_USB_stick
https://r2.community.samsung.com/t5/Tech-Talk/Installing-and-running-Ubuntu-and-other-Linux-OS-flavors-on-your/td-p/3534921
https://www.cyberciti.biz/faq/marvell-88w8335-chipset-netgear-wg311-pcicard-driver/
https://developer.android.com/studio/run/emulator#install
https://youtu.be/8XZjeNqVD50
https://youtu.be/C1R8N6UA980
https://superuser.com/questions/6892/sync-remote-folders-on-linux#6896
https://askubuntu.com/questions/16621/how-to-set-the-default-browser-from-the-command-line
https://cli.r-lib.org/articles/semantic-cli.html
https://alternativeto.net/software/tuxi/about/
https://docs.flatpak.org/en/latest/usb-drives.html
https://askubuntu.com/questions/446156/pause-execution-and-wait-for-user-input
https://askubuntu.com/questions/484993/run-command-on-anothernew-terminal-window
https://askubuntu.com/questions/46627/how-can-i-make-a-script-that-opens-terminal-windows-and-executes-commands-in-the
https://askubuntu.com/questions/883777/bash-script-to-open-multiple-terminal-widows
https://unix.stackexchange.com/questions/155417/a-set-of-libraries-like-ncurses-in-a-shell-script
https://gitlab.com/rwxrob/dotfiles
https://garudalinux.org/
https://forum.garudalinux.org/
https://wiki.garudalinux.org/
https://garudalinux.org/downloads.html
https://distrowatch.com/table.php?distribution=garuda
https://www.kali.org/docs/development/live-build-a-custom-kali-iso/
https://www.keekass.com/videos/61783/highlights-of-transgirl-porno-7-compilation/?utm_source=oklax&utm_medium=oklax&utm_campaign=oklax
https://www.bemyhole.com/v/hanna-rios-vs-asia-devil-mireja-ts-challenge-new-edition-450557046223/
https://www.bemyhole.com/v/top-20-hottest-trans-babes-part-1-20-11-transsexualangel-290550043723/
https://stackoverflow.com/questions/10679188/casing-arrow-keys-in-bash
https://chessmood.com/course/win-won-positions
https://chessmood.com/course/save-lost-positions
https://lichess.org/@/Avetik_ChessMood/blog/slp-method-how-to-save-lost-chess-positions/C44ecQCz
https://chessmood.com/blog/slp-method-how-to-save-lost-positions
https://chessmood.com/course/opening-principles
https://chessmood.com/course/avetik-grigoryan-best-games
https://chessmood.com/course/gabuzyan-best-games
https://chessmood.com/blog/win-won-games</A>
https://status.garudalinux.org/
https://connect.mozilla.org/
https://unix.stackexchange.com/questions/145294/how-to-continue-a-script-after-it-reboots-the-machine
https://www.linuxtopia.org/
https://askubuntu.com/questions/64833/vi-shortcut-to-delete-until-the-next-x-character
https://www.reddit.com/r/vim/comments/11ntbmv/whats_your_vimrc_setup_for_2023/
https://www.reddit.com/r/vimporn/
https://www.reddit.com/r/vim/comments/a9xri2/any_sites_that_show_off_others_vim_configs/
https://wiki.archlinux.org/title/Dotfiles
https://superuser.com/questions/345877/prepend-only-lines-with-text-in-vim
https://www.q4os.org/dqa009.html
https://askubuntu.com/questions/641683/how-can-i-send-commands-to-specific-terminal-windows
https://opensource.com/article/18/9/linux-iptables-firewalld
https://bash-hackers.gabe565.com/
https://unix.stackexchange.com/questions/146570/arrow-key-enter-menu
https://unix.stackexchange.com/questions/539202/looking-for-command-line-package-for-showing-inline-text-based-menu-selector-wit
https://unix.stackexchange.com/questions/715893/bash-completely-cli-interactive-menu
https://unix.stackexchange.com/questions/480081/bash-question-using-read-can-i-capture-a-single-char-or-arrow-key-on-keyup
https://stackoverflow.com/questions/58557541/how-to-create-a-list-of-option-and-selecting-it-using-arrow-key-in-shell
https://asciinema.org/
https://yadm.io/docs/examples#
https://www.freecodecamp.org/news/tag/linux/
https://crates.io/crates/dotter
https://packages.ubuntu.com/search?keywords=xulext-ubufox
https://support.mozilla.org/en-US/questions/1197798
https://askubuntu.com/questions/330937/is-it-possible-to-open-an-ubuntu-app-from-html
https://kitchen.nine.com.au/bourke-street-bakery-cookbook
https://www.hongkiat.com/blog/extract-text-from-images-imgclip/
https://superuser.com/questions/46730/convert-image-to-text
https://www.addictivetips.com/ubuntu-linux-tips/copy-text-from-pictures-on-linux-with-textsnatcher/
https://www.howtogeek.com/682389/how-to-do-ocr-from-the-linux-command-line-using-tesseract/
https://betterprogramming.pub/how-to-monitor-your-machine-with-one-spectacular-cli-tool-a1c3313a409a
https://www.reddit.com/r/vim/comments/t9lm4x/whats_your_best_autocmd/
https://taskwarrior.org/tools/
https://docs.ansible.com/ansible/latest/collections/community/general/xfconf_module.html
https://searx.garudalinux.org/
https://help.ubuntu.com/community/Grub2/ISOBoot
https://medevel.com/srss/#gsc.tab=0
https://radicale.org/v3.html
https://www.linuxtoday.com/
https://www.davidsimmons.com/soft/xtermhacks/
https://tuxurls.com/
https://linuxhint.com/best_ubuntu_news_websites_blogs/
https://www.makeuseof.com/tag/websites-linux-users/
https://alltop.com/linux
https://sourceforge.net/projects/voyagerlive/files/
https://sourceforge.net/projects/ultimateedition/files/
https://www.omglinux.com/chatgpt-command-line/
https://codepen.io/ianfarb/pen/mJZaGd
https://codepen.io/EduardL/pen/jObzJB
https://codepen.io/baochn/pen/yLvPeaG
https://codepen.io/h4yfans/pen/VjKBWy
https://stackoverflow.com/questions/22566373/tmux-how-to-restore-layout-after-changing-it-with-select-layout-or-next-layout
https://www.learnoutloud.com/Free-Audio-Video/Philosophy/-/Slavoj-Zizek-On-Melancholy/81739
https://getmusicbee.com/forum/index.php?topic=30205.30
https://superuser.com/questions/538112/meaningful-thumbnails-for-a-video-using-ffmpeg
https://www.gnu.org/software/grub/manual/grub/grub.html#Installing-GRUB-using-grub_002dinstall
https://getmusicbee.com/forum/index.php?topic=30205.0
https://www.reddit.com/r/ranger/comments/12ibt7t/how_to_changeadd_custom_text_in_ranger_commands/?rdt=40369
https://superuser.com/questions/1048647/how-to-define-new-commands-in-the-ranger-file-manager
https://unix.stackexchange.com/questions/65077/is-it-possible-to-see-cp-speed-and-percent-copied
https://www.cyberciti.biz/open-source/command-line-hacks/ag-supercharge-string-search-through-directory-hierarchy/
https://www.reddit.com/r/bash/comments/khefxh/how_to_rearrange_bash_shell_script_output_in/?rdt=64851
https://documentaryheaven.com/rupert-inside-north-korea/
https://www.tutorialspoint.com/unix_commands/tput.htm
https://askubuntu.com/questions/68175/how-to-create-script-with-auto-complete
https://www.falkon.org/
https://store.falkon.org/
https://www.kde.org/
https://planet.kde.org/
https://wiki.syslinux.org/wiki/index.php?title=MEMDISK
https://www.explainshell.com/
https://stackoverflow.com/questions/13433903/convert-all-linux-man-pages-to-text-html-or-markdown
https://taskwarrior.org/docs/udas/
https://taskwarrior.org/docs/report/
https://peter.sh/
https://www.htmlgoodies.com/css/displaying-rss-feeds-with-xhtml-css-and-jquery/
https://dev.to/heraldofsolace/replace-your-existing-unix-utilities-with-these-modern-alternatives-2bfo
https://chess.stackexchange.com/questions/44875/how-to-play-as-black-in-the-exchange-caro-kann
https://musicbee.fandom.com/wiki/Skins
https://tails.net/doc/encryption_and_privacy/encrypted_volumes/index.en.html
https://superuser.com/questions/584883/how-can-i-access-volumes-encrypted-with-luks-dm-crypt-from-windows
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/encrypting-block-devices-using-luks_security-hardening
https://www.redhat.com/sysadmin/disk-encryption-luks
https://www.eff.org/
https://start.garudalinux.org/
https://stackoverflow.com/questions/3916191/download-data-url-file
https://www.reutersagency.com/en/reutersbest/reuters-best-rss-feeds/
https://beebom.com/how-use-chatgpt-linux-terminal/
https://www.trackawesomelist.com/
https://bbs.archlinux.org/viewtopic.php?id=243226/
https://www.redhat.com/sysadmin/learn-bash-scripting/
https://www.hostinger.com/tutorials/bash-script-example/
https://proprivacy.com/privacy-service/comparison/private-search-engines/
https://stackoverflow.com/questions/51142253/add-python-support-to-vim/
https://azero.dev/#/accounts/
https://wiki.alpinelinux.org/wiki/Main_Page/
https://serverfault.com/questions/629778/which-open-source-program-is-similar-to-the-linux-dialog-command/
https://stackoverflow.com/questions/25929369/which-open-source-program-is-similar-to-the-linux-dialog-command/
https://linuxconfig.org/tag/bash/
https://stackoverflow.com/questions/42371156/bash-dialog-inputbox-with-variable-entered/
https://linuxconfig.org/bash-scripting-tutorial-for-beginners/
https://www.binance.com/en/
https://www.bitaddress.org/bitaddress.org-v3.3.0-SHA256-dec17c07685e1870960903d8f58090475b25af946fe95a734f88408cef4aa194.html/
https://ux.stackexchange.com/questions/120001/alternatives-to-modal-dialog-for-simple-forms/
https://browserleaks.com/canvas/
https://cezex.io/#/price-all/
https://torguard.net/checkmytorrentipaddress.php?hash=65fd3f647d2a679bdc4ad2e47bbda2b1043eaba2/
https://discordapp.com/invite/KEFErEx/
https://www.guru99.com/data-communication-computer-network-tutorial.html/
https://www.ohchr.org/en/instruments-mechanisms/instruments/convention-against-torture-and-other-cruel-inhuman-or-degrading/
https://blog.self.li/post/74294988486/creating-a-post-installation-script-for-ubuntu/
https://walletinvestor.com/converter/
https://talosintelligence.com/fullpage_maps/pulse?__cf_chl_jschl_tk__=d8606de8e8d992f81979cff17898eac51835e80e-1615699239-0-AS8Ebf8Q8sHMWu1iKhC-l6hylqTP1PExnMqVp9OMbXnjXXGe4PwnTbDXfluWlzgEe5tW02keOWjQvDQzcJSv_0HMH9_cGhJd13AW9coDbCFA2jVzAvTEZzTe3KZm84D38oDN_kV1emLlyXZrDSJWU9R8sR4o5u9StkTIFyKzMYlPP7pdwDT4zUZmQEfyjFNsZIVzgK6RXyOwwyAYDJDZMFYBIc3n8dqV2ngGJxdUUQVn4cNw5KMWvANY3rg5Rq-BB4GM_WOOwAbqAPwWKnMEl6EWsPzHF-6lvXojUYyPlzZ1vq3I43DbDFQ2_JLxXWoNr3-A40GW287DtWRIfOy_VhF6TgDwv3LCQ1H0R2q7CSw9CLn1GBEk1lOakNH41FGjTPPWhaKviE8x1y9NyDCPok4tnKhqiqKDVxd4gt40Vr1i/
https://www.hackthebox.com/hacker/infosec-careers/
https://cointool.app/dashboard/
https://www.debian.org/doc/user-manuals#debian-handbook/
https://www.deepl.com/translator/
https://vimeo.com/user1690209/
https://www.dexlab.space/mintinglab/spl-token/
https://alternativeto.net/software/dialog/?platform=linux/
https://www.digitalattackmap.com/#anim=1&color=0&country=ALL&list=0&time=18205&view=map/
https://wiki.alpinelinux.org/wiki/Dualbooting/
https://youtu.be/Q...
https://ether-mixer.org/start-mixing.html/
https://explainshell.com/explain?cmd=pandoc/
https://vi.stackexchange.com/questions/39627/export-libreoffice-thesaurus-to-vim-compatible-format-with-a-macro/
https://www.fireeye.com/cyber-map/threat-map.html/
https://stackoverflow.com/questions/946189/how-can-i-set-default-homepage-in-ff-and-chrome-via-javascript/
https://wiki.mozilla.org/Firefox/CommandLineOptions/
https://www.tandfonline.com/doi/full/10.1080/14753634.2013.778485/
https://gnupg.org/documentation/howtos.html/
https://www.hackthebox.com/blog/
https://www.hackthebox.com/hacker/hacking-labs/
https://humanrights.gov.au/quick-guide/12040/
https://hide.me/en/proxy/
https://wiki.alpinelinux.org/wiki/Hosting_Web/Email_services_on_Alpine/
https://vi.stackexchange.com/questions/7656/how-do-i-get-multiple-vimwikis-to-show-under-vimwiki-open-index-in-the-gvim/
https://opensource.com/life/15/3/creating-split-screen-shots-kdenlive/
https://medium.com/devnetwork/how-to-create-your-own-custom-terminal-commands-c5008782a78e/
https://stackoverflow.com/questions/39337075/how-to-delete-text-between-all-braces-in-vim/
https://9to5linux.com/how-to-search-for-text-within-files-and-folders-in-linux/
https://medium.com/@jimmashuke/how-to-stop-that-annoying-sudo-password-prompt-in-linux-b2b72b9c2f55/
https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced/
https://docs.docker.com/engine/install/debian/#set-up-the-repository/
https://cararegistrasi.com/7HWEkta1V8pTer...
https://wiki.alpinelinux.org/wiki/Install_to_disk/
https://www.perturb.org/content/iptables-rules.html/
https://docs.oracle.com/javase/
https://0x64marsh.com/?p=314/
https://www.digi77.com/software/kodachi/Kodachi-Log.txt/
https://nim-lang.org/learn.html/
https://nodejs.dev/learn/
https://superuser.com/questions/1224532/get-links-from-an-html-page/
https://unix.stackexchange.com/questions/452101/how-to-keep-only-latest-file-in-the-folder-and-move-older-files-to-archive-locat/
https://linuxcommand.org/lc3_adv_dialog.php/
https://www.foxinfotech.in/2019/04/linux-dialog-examples.html/
https://docs.docker.com/engine/install/linux-postinstall/#configuring-remote-access-with-systemd-unit-file/
https://in-the-sky.org/satmap_worldmap.php/
https://mint.bitcoin.com/#/configure/
https://pastebin.com/P7rwMFLq/
https://www.thelinuxrain.org/articles/multiple-item-data-entry-with-yad/
https://pastebin.com/yZM8zGwv/
https://medium.com/geekculture/neovim-configuration-for-beginners-b2116dbbde84/
https://raspberrypi.stackexchange.com/questions/110799/wifi-not-working-after-installing-openmediavault-omv-5-in-rpi-4/
https://phoenixnap.com/kb/nmap-command-linux-examples/
https://csandker.io/2021/01/10/Offensive-Windows-IPC-1-NamedPipes.html/
https://csandker.io/2021/02/21/Offensive-Windows-IPC-2-RPC.html/
https://csandker.io/2022/05/24/Offensive-Windows-IPC-3-ALPC.html/
https://messari.io/onchainfx/
https://www.zend2.com/#/
https://wiki.alioth.net/index.php/Oolite_Main_Page/
https://www.opentraintimes.com/maps/
https://php.net/manual/en/index.php/
https://wiki.alpinelinux.org/wiki/Post_installation/
https://vim.fandom.com/wiki/Power_of_g/
https://wiki.gnome.org/action/show/Projects/Zenity?action=show/
https://www.brewology.com/?cat=4/
https://www.brewology.com/psn/downloader.php?ref=news/
https://stackoverflow.com/posts/41463292/revisions/
https://www.baeldung.com/linux/run-command-start-up/
https://geoxc-apps2.bd.esri.com/Visualization/sat2/index.html/
https://vi.stackexchange.com/questions/8839/how-i-configure-vim-for-use-with-netrw/
https://vi.stackexchange.com/questions/19357/search-through-entire-vimwiki/
https://stackoverflow.com/questions/2512362/how-can-i-can-insert-the-contents-of-a-file-into-another-file-right-before-a-spe/
https://unix.stackexchange.com/questions/99350/how-to-insert-text-before-the-first-line-of-a-file/
https://unix.stackexchange.com/questions/337435/sed-insert-file-at-top-of-another/
https://www.abs.gov.au/articles/sexual-harassment/
https://stackoverflow.com/questions/2314750/how-to-assign-the-output-of-a-bash-command-to-a-variable/
https://stackoverflow.com/questions/37644634/how-to-use-bash-dialog-yesno-correctly/
https://www.redtube.com/playlist/3434751/
https://securitycenter.sonicwall.com/m/page/worldwide-attacks/
https://securitycenter.sonicwall.com/m/page/capture-labs-threat-metrics/
https://www.redhat.com/sysadmin/sshfs/
https://www.ssllabs.com/ssltest/viewMyClient.html/
https://www.vim.org/scripts/script.php?script_id=3465/
https://kb.mozillazine.org/Talk:Firefox_links/
https://www.psychologytoday.com/us/blog/cutting-edge-leadership/201811/the-5-steps-dehumanization/
https://www.debian.org/doc/manuals/debian-handbook/index.en.html/
https://web.threema.ch/#!/welcome/
https://opensecuritytraining.info/Training.html/
https://stackoverflow.com/questions/66866818/how-to-change-nvim-path-to-config/
https://manpages.ubuntu.com/manpages/kinetic/en/man1/pandoc.1.html/
https://askubuntu.com/questions/500359/efi-boot-partition-and-biosgrub-partition/
https://opensource.com/article/20/1/vim-task-list-reddit-twitter/
https://medium.com/@felipe.anjos/vim-for-web-development-html-css-in-2020-95576d9b21ad/
https://www.naperwrimo.org/wiki/index.php?title=Vim_for_Writers/
https://vi.stackexchange.com/questions/28505/vimwiki-create-a-smart-index-page-for-subdir-section-of-wiki/
https://dev.to/psiho/vimwiki-how-to-automate-wikis-per-project-folder-neovim-3k72/
https://twitter.com/warith2020?lang=en/
https://developer.mozilla.org/en-US/docs/Web/API/
https://portswigger.net/web-security/
https://linuxconfig.org/webdav-server-setup-on-ubuntu-linux/
https://www.psychologytoday.com/us/blog/the-web-violence/201806/what-is-dehumanization-anyway/
https://wpscan.com/wordpresses/
https://unix.stackexchange.com/questions/378373/add-virtual-output-to-xorg/
https://bbs.archlinux.org/viewtopic.php?id=202463/
https://yad-guide.ingk.se/html/yad-html.html/
https://codeberg.org/NRZCode/yad-examples/src/branch/master/player.sh/
https://codeberg.org/NRZCode/yad-examples/src/branch/master/sysinfo-notebook.sh/
https://codeberg.org/NRZCode/yad-examples/src/branch/master/tabs.sh/
https://blog.teamtreehouse.com/
https://www.smashingmagazine.com/2018/02/comprehensive-guide-ui-design/
https://www.usability.gov/what-and-why/user-interface-design.html
https://developer-old.gnome.org/NetworkManager/stable/nmcli-examples.html
https://developer-old.gnome.org/NetworkManager/stable/nmcli.html
https://live-team.pages.debian.net/live-manual/html/live-manual/examples.en.html
https://www.documentarytube.com/
https://topdocumentaryfilms.com/
https://documentaryheaven.com/
https://i2psearch.com/discover
https://i2psearch.com/
https://bash.forret.com/2022/02/the-bash-hackers-wiki/
https://news.ycombinator.com/item?id=22382686
https://bash.forret.com/tools/
https://wiki.bash-hackers.org/
https://gitconnected.com/learn/linux-system-administration/the-bash-hackers-wiki-ddcb96
https://gitlab.com/kalilinux/recipes/live-build-config-examples
https://gitlab.com/kalilinux/build-scripts/live-build-config.git
https://gitlab.com/kalilinux/build-scripts/live-build-config
https://gitlab.com/kalilinux
https://superuser.com/questions/416881/directory-bookmarking-in-linux
https://www.pornhat.com/video/hot-for-teacher-01053/?ad_sub=321&ad_sub=321&ad_sub=321
https://www.pornhat.com/video/bbw-porn-with-conquering-charlie-from-60plusmilfs/?ad_sub=321
https://ok.xxx/video/240184/?ad_sub=321
https://ok.xxx/video/235795/?ad_sub=321
https://www.freecodecamp.org/news/bashrc-customization-guide/
https://www.rat.xxx/videos/22798/busty-blonde-cougar-seduced-endowed-nerd-into-sex/?utm_source=zbporn.com&utm_medium=referral&utm_campaign=friendly_videos_thumbs
https://www.q4os.org/dqa002.html
https://www.q4os.org/dqa017.html
https://www.q4os.org/forum/index.php
https://superuser.com/questions/1785891/how-to-modify-linux-iso-like-ubuntu-and-add-my-custom-bash-to-it
https://www.unixmen.com/edit-iso-files-using-mkisofs-in-linux/
https://www.linuxuprising.com/2018/07/how-to-customize-ubuntu-or-linux-mint.html
https://www.linuxuprising.com/2021/03/find-and-remove-duplicate-files-similar.html
https://www.gumtree.com.au/s-ad/ashfield/desktops/acer-inspire-1601x-sff-desktop-no-drive-/1316336644
https://randomgeekery.org/post/2020/04/taskwarrior-custom-reports/
https://taskwarrior.org/docs/commands/list/
https://www.bestoftheleft.com/
https://invidious.privacyredirect.com/
https://topdocumentaryfilms.com/why-universe-exist/
https://blog.logrocket.com/7-tui-libraries-interactive-terminal-apps/
https://www.antixforum.com/forums/topic/100-awesome-and-must-have-tui-linux-apps/
https://fedoramagazine.org/writing-useful-terminal-tui-on-linux-with-dialog-and-jq/
https://dev.to/lazy_code/5-best-python-tui-libraries-for-building-text-based-user-interfaces-5fdi
https://terminaltrove.com/isd/
https://www.reddit.com/r/linux/comments/1chnatf/app_idea_a_tui_notetaking_app_for_students_that/
https://www.linuxlinks.com/100-great-must-have-cli-linux-applications/
https://www.linuxlinks.com/timr-tui-organize-time/
http://emmet.io/</A>
https://taskwarrior.org. It is to display upcoming tasks and task details as well as to create and modify them.</A>
https://taskwarrior.org. It is to display upcoming tasks and task details as well as to create and modify them. - cinatic/taskwhisperer
https://wails.io/docs/introduction/
https://go.dev/doc/install
https://superfile.netlify.app/getting-started/installation/
https://therecipedb.vercel.app/
https://stackoverflow.com/questions/203684/how-can-i-use-nlp-to-parse-recipe-ingredients
https://www.tnaflix.com/blonde-porn/Juiciest-cougars-and-hot-milfs-in-one-compilation-from-mylf-site/video9962990?utm_source=Nudevista&utm_medium=web&utm_campaign=Nudevista+Camp</A>
https://ghostty.org/docs/config/keybind
https://www.cyberciti.biz/faq/dhclient-etcresolvconf-hooks/
https://www.amateurporn.me/tags/
https://www.amateurporn.me/search/fun-charlie/
https://www.transpornsites.com/
https://www.sheflix.com/categories/compilation/
https://ia600802.us.archive.org/view_archive.php?archive=/12/items/ps2-iso-backups-7z/Capcom%20Fighting%20Evolution.7z
https://ia800802.us.archive.org/view_archive.php?archive=/12/items/ps2-iso-backups-7z/Capcom%20Classics%20Collection%20Vol.%202.7z
https://ia800802.us.archive.org/view_archive.php?archive=/12/items/ps2-iso-backups-7z/Capcom%20Classics%20Collection%20Vol.%201.7z
https://archive.org/download/PS2CollectionPart2ByGhostware
https://archive.org/details/@sonaje
https://archive.org/details/kodi_archive?page=4
https://archive.org/search?query=subject%3A%22PS2%22
https://archive.org/details/yugioh-jap
https://archive.org/details/sony-play-station-2-firmware-tosec-v-2012-09-08-cm
https://sw.kovidgoyal.net/kitty/#kittens
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.listen_on
https://www.reddit.com/r/KittyTerminal/comments/w7u5nl/window_sizes_in_saved_layouts/
https://paul-nameless.com/mastering-kitty.html
https://ubuntusway.com/downloads.php
https://searx.org/search
https://www.bigtitslust.com/videos/641084/piwi-104/?utm_source=donnie
https://www.bigtitslust.com/videos/614984/piwi-133/
https://www.sortporn.com/videos/508864/piwi-110/
https://hotmovs.com/videos/5458129/piwi-109/?promo=10376
https://hotmovs.com/videos/5452048/piwi-111/?fr=5452048&rp=1
https://docs.vllm.ai/en/latest/features/quantization/gguf.html
https://superfile.netlify.app/getting-started/tutorial/
https://superfile.netlify.app/list/plugin-list/
https://ariya.io/2020/05/nix-package-manager-on-ubuntu-or-debian
https://ca.pinterest.com/pin/repottt-ideogram--545146729911232971/
https://coolpub.com/centralize-kodi-management-part-2/
https://www.reddit.com/r/kodi/comments/savyyo/how_to_get_movie_thumbnails_to_display_on_kodi/
https://kodi.wiki/view/Movie_artwork
https://unix.stackexchange.com/questions/704370/initramfs-got-corrupted-misconfigured-how-to-boot-properly
https://unix.stackexchange.com/questions/709783/cannot-find-a-grub-drive-for-dev-sda1-check-your-device-map
https://stackoverflow.com/questions/73343207/how-do-i-make-a-tui-dialog-box
https://archive.org/details/archlinux_pkg_ttf-nerd-fonts-symbols-2048-em
https://www.reddit.com/r/unixporn/comments/wmp38t/tty_dvtm_give_tty_some_love/
https://www.brain-dump.org/projects/dvtm/
https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
https://askubuntu.com/questions/1258409/can-one-watch-video-in-terminal-command-line
https://gitlab.com/dwt1/dmscripts
https://dwm.suckless.org/patches/awesomebar/
